### ISSUE TITLE
How to use Distriqt IronSource ANE?

### ISSUE THREAD

**Issue by harry90** [distriqt/ANE-IronSource#1]
1. Could you explain why you provide an ironSource ANE? 

2. Why should we use your ANE instead of the ANEs provided by IronSource itself? Or is it an addition to them? 

3. What about the Mediation Adapters?

**Comment by marchbold** [comment]
> IronSource does provide an ANE independent of this ANE. We developed this ANE so we can update the ANE to match the latest native versions without waiting for updates from IronSource directly, which seem to lag behind the native SDKs.

This isn't really something we expect many to use, just something we developed for ourselves and have made public.

The exisiting mediators will work with this ANE, it's just to make sure we can use the latest native SDK and not wait for Ironsource to update the ANE.

**Comment by harry90** [comment]
So we could replace IronSource_v6.8.0.ane with your ANE?

**Comment by harry90** [comment]
And what about adding the Eventlisteners and methods, is this the same code?

**Comment by marchbold** [comment]
If you wish, 

you can see our example here but pretty much the same:

https://github.com/distriqt/ANE-IronSource/blob/master/example/starling/src/com/distriqt/test/ironsource/IronSourceTests.as

We have defined an event class with definitions of the event constants as well to make the code clearer.

**Comment by marchbold** [comment]
Only use this if you are having issues with their version though.

**Comment by harry90** [comment]
Well I have a problem on iOS with Rewarded Video ads from Supersonic using their Air Plugin. The onRewardedVideoAdRewarded event is never called on the client, so the users don't get rewarded for watching the ads. I recognized that the users try it several times, having to watch an ad each time, then they give up and deinstall the app. This only happens with ads from Supersonic. 

Don't know if this has to do with the ANE?

**Comment by marchbold** [comment]
I haven't used the supersonic mediator so I can't confirm that, but feel free to see if this ane helps. It just has an updated version of the the SDK and our implementation of the ANE wrapper. It may help.

**Comment by harry90** [comment]
I already implemented a workaround on this. But yes good idea, I will try if your ANE could solve the problem. Thx
