### ISSUE TITLE
Still crashing on iOS after rewarded video after last update

### ISSUE THREAD

**Issue by noamgat** [distriqt/ANE-IronSource#10]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this and ask your question.

This is on version 0.2.246 of the SDK (which explicitly states the ios fix)

##### Expected behaviour
After rewarded video, game continues to function

##### Actual behaviour
crash. Native crash log shows segmentation fault.

##### Environment 

- AIR SDK version: 32
- Device OS: iOS 10/11
- Device version: Tested on iPhone 6 and iPad 4
- Development IDE: Adobe Animate
- Development OS:Windows

##### Logs

[Super Mechs-2019-10-20-164507.zip](https://github.com/distriqt/ANE-IronSource/files/3747935/Super.Mechs-2019-10-20-164507.zip)

Device logs if relevant

Incident Identifier: 39849074-5001-4FA6-939D-A53926FB6970
CrashReporter Key:   a46930b5f3fe4e4567f29b285a9507bdd0a23a21
Hardware Model:      iPad3,4
Process:             Super Mechs [786]
Path:                /private/var/containers/Bundle/Application/F9F8DE71-81A3-425E-9A56-C4A92167C901/Super Mechs.app/Super Mechs
Identifier:          com.supermechs.superapp
Version:             7.400.0 (7.400)
Code Type:           ARM (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.supermechs.superapp [526]

Date/Time:           2019-10-20 16:45:06.9657 +0300
Launch Time:         2019-10-20 16:38:08.0000 +0300
OS Version:          iPhone OS 10.3.3 (14G60)
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x000001f4
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  0

**Comment by marchbold** [comment]
Can you post the device logs? https://airnativeextensions.github.io/tutorials/device-logs

And ideally some code to reproduce the issue.
