### ISSUE TITLE
[Request] New Ironsource SDK

### ISSUE THREAD

**Issue by sweetnitro** [distriqt/ANE-IronSource#14]
Hello,

Ironsource has released a new SDK, we are specially interested by it because on the last one we have a high crash rate on iOS (due to Admob adapter).

The issue is that with the new admob adapter, it crashes on compilation (and it doesn't crash if we include their last SDK).

So we suppose it crashes because your ANE is not up to date. Are you planning to update it?

Regards

**Comment by marchbold** [comment]
I'll see if I can find some time to update this ANE but it's not part of our normal update process as it's a free one we just update when we need. 

Have IronSource updated their main ANE? Could be worth trying if you need it urgently?

**Comment by sweetnitro** [comment]
Yes they have updated their main ANE.
But don't worry it's not urgent :)

**Comment by marchbold** [comment]
Latest SDK v7.0.0 has just been released.

Let us know if you have any issues.
