### ISSUE TITLE
Error on show ad/video and app left in blocking state

### ISSUE THREAD

**Issue by neuronix** [distriqt/ANE-IronSource#16]
Hi guys,

We updated our iOS app with the latest release and we also updated all the IS adapters (other than FB) to the latest version (4.1.6+ as well as any extra required SDK anes as indicated in the IS documentation).

When testing interstitials, every single time, the app sort of goes to a mid-ground state (see screenshot) where the screen is not usable. The AS3 gets an error callback but the event.data is empty so no apparent reason why.  Swiping down brings the app back to the foreground.

When testing videos, this will happen most of the time, but sometimes the IS test video works and sometimes AdMob works.

I checked your documentation to see if there were any changes since the previous release but none that I can see.

Tested on ios 13, iPhone XS.

Thanks for your help guys :)

![IMG_2667](https://user-images.githubusercontent.com/219800/91861299-ee7cc980-ec6c-11ea-9d19-056f2d35fe06.PNG)

Edit: added missing screenshot. You can see the app in a "mid" ground state, splash screen visible on the edges, app not filling the screen.

**Comment by marchbold** [comment]
Interesting, 

Just confirming this is using the release from a few days ago with v7 of the IronSource SDK?

**Comment by neuronix** [comment]
Yes indeed, I downloaded the latest ane from this repository yesterday. Today we just got an email from IS announcing SDK 7, do you think some adapters are out of date? Did you test with adapters or without?

Thanks for your support!

**Comment by marchbold** [comment]
Definitely guess the mediators are outdated, but that wouldn't cause the issue with Ironsource. Any clues as to how to reproduce?

**Comment by neuronix** [comment]
Well it happens every time on my device for interstitials at least. I will send you our xml and other build details.

**Comment by neuronix** [comment]
Okay, so I tried 2 builds:
1. Only your ANE + FB stuff: working fine
2. Only your ANE + FB stuff + Admob Adapter: issues every time Admob runs, IS working fine.

So I guess the adapters are outdated and we will have to wait for IS to update them.

**Comment by marchbold** [comment]
Okay, thanks for investigating, but yes that would be my guess. 

If you need something urgently we could put one together for you, just contact airnativeextensions@distriqt.com.

**Comment by neuronix** [comment]
Hi guys, just a quick question regarding SDK 7, this is the answer from Ironsource when asked about updating their adapters for SDK 7:

"AdobeAIR doesn’t support SKAdNetwork code at the moment, and it can’t be passed to xCode. Therefore, we will not release SDK 7 for AIR until they release support for the SKAN functions."

I don't believe this, since you can wrap any code in an ANE and you don't seem to have run into any issues yourselves, could you give me your feedback on your experience integrating SDK 7?

**Comment by marchbold** [comment]
@neuronix I believe they will be referring to the new permissions request for the IDFA. Yes you are right they could implement it in their ANE.  We are adding these functions to one of our ANEs separately, we haven't added it to this extension.
