### ISSUE TITLE
Banner Ad support

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-IronSource#18]
Hi
Will banner ad support be added?

**Comment by marchbold** [comment]
Hi,

This is a free extension so we only update it when we have spare time or when a client sponsors the development. I will add this into the schedule, but if you have need for it you can contact our custom development team at airnativeextensions@distriqt.com

Cheers

**Comment by marchbold** [comment]
Banner Ads are now available

https://docs.airnativeextensions.com/docs/ironsource/banner-ads
