### ISSUE TITLE
Tapjoy and Chartboost

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-IronSource#19]
Hi!

Changelog from https://developers.ironsrc.com/ironsource-mobile/air/sdk-change-log/

> Important! This SDK version requires you to update all your network adapters to the latest version (or any version compatible with SDK Version 6.17.0). This will ensure your configuration in up-to-date. In addition, Tapjoy and Chartboost are no longer supported for AdobeAir platform. Please make sure to remove these adapters, prior to upgrading to this version.

Does it mean that I can not use Tapjoy and Chartboost with your ANEs too?
I have already had integrations there.

Thx!

**Comment by marchbold** [comment]
All the mediators here are working with the latest release of the ironsource ANE published here. Our ANE has been updated to ironSource v7 and matching mediation sdks

They probably won't work with the official ironSource ANE as it is still on v6.17.0.

**Comment by Mintonist** [comment]
Thx!
You have done great job!
