### ISSUE TITLE
Add the method getAdvertiserId

### ISSUE THREAD

**Issue by noamgat** [distriqt/ANE-IronSource#2]
The original IronSource implementation has the method getAdvertiserId and we use it for analytics.

it is used like that: IronSource.instance.getAdvertiserId()
its signature is: getAdvertiserId():String

Is it possible to add the same method to this wrapper?

**Comment by marchbold** [comment]
Will get this added as soon as possible

**Comment by marchbold** [comment]
In the meantime you should be able to use this ANE to get this information 

https://github.com/distriqt/ANE-IDFA

**Comment by noamgat** [comment]
Thanks a lot for this update!
