### ISSUE TITLE
Can you provide com.distriqt.IronSource.swc and Offerwall question

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-IronSource#20]
Hi!

Can you provide com.distriqt.IronSource.**swc**?

I noticed you add Offerwall support. Is it IronSource Offerwals?
Can I show for example TapJoy Offerwall with this ANEs?

**Comment by marchbold** [comment]
This is ironsource offerwalls, I'm not sure if mediation works with the offerwall, you'd have to ask IronSource about that.

I'll get the swc added in the next build but I've attached it here for you:

[com.distriqt.IronSource.swc.zip](https://github.com/distriqt/ANE-IronSource/files/5832756/com.distriqt.IronSource.swc.zip)
