### ISSUE TITLE
Issue with Admob on iOS

### ISSUE THREAD

**Issue by sweetnitro** [distriqt/ANE-IronSource#21]
Hello,

We have an issue with Admob on iOS, when we want to watch a video it triggers an error and "lock" the screen (touch doesn't respond anymore). Error seems to be: "INTERNAL: AdMob:RVAdFailedWithError:The provided view controller is not being presented., code:17" but herewith the complete logs. For the other networks no issues and Admob is working perfectly on Android.
Herewith application.xml just in case: [application.xml.txt](https://github.com/distriqt/ANE-IronSource/files/5942700/application.xml.txt)

Otherwise you have a small mistake (that can cost a few hours to find out ^^') on your documentation here: https://docs.airnativeextensions.com/docs/ironsource/add-the-extension
You've written provider
        android:name="com.ironsource.lifecycle.IronsourceLifecycleProvider"
        android:authorities="air.com.distriqt.test.IronsourceLifecycleProvider"
Except of provider
        android:name="com.ironsource.lifecycle.IronsourceLifecycleProvider"
        android:authorities="APPLICATION_PACKAGE.IronsourceLifecycleProvider"

We've updated around 20 of your ANEs without any issues except this one so good job guys :)

Thank you!

##### Logs
```
default 10:05:14.023878+0100 XXXXXX [ironSource SDK] API: IronSource: hasRewardedVideo true
default 10:05:14.023919+0100 XXXXXX com.distriqt.IronSource::isRewardedVideoCappedForPlacement: auctions
default 10:05:14.024245+0100 XXXXXX 00:10 VideosService videoStart
default 10:05:14.024295+0100 XXXXXX com.distriqt.IronSource::showRewardedVideo
default 10:05:14.024333+0100 XXXXXX [ironSource SDK] API: IronSource: hasRewardedVideo true
default 10:05:14.024635+0100 XXXXXX [ironSource SDK] API: showRV with placement name auctions
default 10:05:14.026859+0100 XXXXXX [ironSource SDK] INTERNAL: AdMob:RVAdFailedWithError:The provided view controller is not being presented., code:17
default 10:05:14.027250+0100 XXXXXX [ironSource SDK] INTERNAL: AdMob: rewardedVideoHasChangedAvailability: NO
default 10:05:14.028951+0100 XXXXXX 0x10a1bec00 - WKApplicationStateTrackingView: View with page [0x10a1bf818, pageProxyID: 22] was removed from a window, _lastObservedStateWasBackground: 0
default 10:05:14.029023+0100 XXXXXX 0x124fd4500 - ~ApplicationStateTracker
default 10:05:14.040334+0100 XXXXXX 0x10a1bf818 - [pageProxyID=22, webPageID=23, PID=4112] WebPageProxy::close:
default 10:05:14.040904+0100 XXXXXX 0x124ffeb08 - [PID=4112] WebProcessCache::canCacheProcess: Not caching process because the cache has no capacity
default 10:05:14.041723+0100 XXXXXX 0x124fde130 - ProcessAssertion() PID 4107 acquiring assertion for process with PID 4112, name '<private>'
default 10:05:14.042602+0100 XXXXXX 0x124fecf80 - [PID=4112, throttler=0x124f9ca98] ProcessThrottler::Activity::invalidate: Ending foreground activity / 'View is visible'
default 10:05:14.042826+0100 XXXXXX 0x124f9ca98 - [PID=4112] ProcessThrottler::sendPrepareToSuspendIPC: isSuspensionImminent: 0
default 10:05:14.043657+0100 XXXXXX 0x124f9ca98 - [PID=4112] ProcessThrottler::sendPrepareToSuspendIPC: Sending PrepareToSuspend(3, isSuspensionImminent: 0) IPC
default 10:05:14.043806+0100 XXXXXX 0x124f9ca98 - [PID=4112] ProcessThrottler::processReadyToSuspend: Updating process assertion to allow suspension
default 10:05:14.043910+0100 XXXXXX 0x124f9ca98 - [PID=4112] ProcessThrottler::setAssertionState: Updating process assertion state to 0 (foregroundActivities: 0, backgroundActivities: 0)
default 10:05:14.044017+0100 XXXXXX 0x124fde850 - ProcessAssertion::setState(0) previousState: 3
default 10:05:14.045763+0100 XXXXXX 0x124f9c900 - WebProcessProxy::didSetAssertionState(0)
default 10:05:14.045927+0100 XXXXXX 0x124f9c900 - WebProcessProxy::didSetAssertionState(Suspended) release all assertions for network process
default 10:05:14.046204+0100 XXXXXX 0x124f9ca98 - [PID=4112] ProcessThrottler::setAssertionState: Updating process assertion state to 1 (foregroundActivities: 0, backgroundActivities: 0)
default 10:05:14.047781+0100 XXXXXX 0x124fde850 - ProcessAssertion::setState(1) previousState: 0
default 10:05:14.049446+0100 XXXXXX 0x124f9c900 - WebProcessProxy::didSetAssertionState(1)
default 10:05:14.049519+0100 XXXXXX 0x124f9c900 - WebProcessProxy::didSetAssertionState(Background) taking background assertion for network process
default 10:05:14.051590+0100 XXXXXX Found 5 implemented methods in 6 delegates
default 10:05:14.053272+0100 XXXXXX 0x10a1bf818 - [pageProxyID=22, webPageID=23, PID=4112] WebPageProxy::destructor:
default 10:05:14.053625+0100 XXXXXX 0x124f9ca98 - [PID=4112] ProcessThrottler::invalidateAllActivities: BEGIN
default 10:05:14.053751+0100 XXXXXX 0x124f9ca98 - [PID=4112] ProcessThrottler::invalidateAllActivities: END
default 10:05:14.054156+0100 XXXXXX 0x124fde850 - ~ProcessAssertion() Releasing process assertion
default 10:05:14.054244+0100 XXXXXX [ironSource SDK] DELEGATE: rewardedVideoDidFailToShowWithError error:The provided view controller is not being presented.
default 10:05:14.054527+0100 XXXXXX [ironSource SDK] DELEGATE: rewardedVideoHasChangedAvailability available:false
```

**Comment by marchbold** [comment]
Hi,

Thanks for pointing out the error in the docs, we had actually just noticed it as well and will have an update shortly. 

Regarding the error, do you have any hints on how to reproduce? It looks like it's going to be something internal to ironsource so not sure what we can do but will report it at the least if we can reproduce it.

Which version of Google Play Services are you using in your app? Have you correctly added the latest additional dependencies (androidx.work and androidx.room)?

**Comment by sweetnitro** [comment]
Hi,

For us whatever the app it doesn't work and this error occurs everytime ironsource is trying to show an Admob video.
androidx.work and androidx.room are only for Android no? Issue is on iOS (on Android everything works fine).

Note that we are compiling with mac os big sur, iOS SDK 14.4 (xcode 12.4) and 33.1.1.345 for Air.

Thanks

**Comment by marchbold** [comment]
Ah apologies, yes those are only for Android. What version of iOS are you encountering the error on?

**Comment by sweetnitro** [comment]
We have 2 devices, one on iOS 13.7 and the other on 14.3
We've tried also just in case with the fewer ANE as possible (to be sure there is no conflict) and also with dependencies here: https://developers.ironsrc.com/ironsource-mobile/air/admob-mediation-guide/#step-4
Both tests were not concluant. It always "freeze" the app with an error.

**Comment by marchbold** [comment]
Okay, will try and find some time to look into it for you.
