### ISSUE TITLE
AppLoving Mediation integration 

### ISSUE THREAD

**Issue by gilil12** [distriqt/ANE-IronSource#22]
Hi,

I am getting the following error when packing the app Using AppLoving mediation on Android:

aapt tool failed:C:\Users\gille\AppData\Local\Temp\ba994ab8-6538-4e7a-8dea-f3e4a38ddeb8\AndroidManifest.xml:164: error: Error: No resource found that matches the given name (at 'theme' with value '@style/com.applovin.mediation.MaxDebuggerActivity.Theme').

Any Help will be appreciated.

Gil

**Comment by marchbold** [comment]
What version of AIR are you using? Please make sure you are using one of the recent 33.1 releases.

**Comment by gilil12** [comment]
Hi,

I am using 33.1.1.259 , is this recent enough?

G.

**Comment by gilil12** [comment]
Hi,

I upgraded to the latest version of air sdk 33.1.1.406 and the error still exists.

G.

**Comment by marchbold** [comment]
What version of java are you using as well? This can have issues when packaging android builds. You need to be using v1.8.x of the JDK.

**Comment by marchbold** [comment]
Ah actually, appears there was an issue in our build. I'm correcting it now and will update shortly.

**Comment by marchbold** [comment]
Can you test this build out for me: 

https://www.dropbox.com/s/u3jcdtjttq02pnp/com.distriqt.IronSource.v2.4.1.zip?dl=0

**Comment by gilil12** [comment]
Hi Michael,

I will check it , and give you a feedback in few hours

Thanks,
G.

**Comment by gilil12** [comment]
Hi Michael,

After updating the ANE , everything is working as expected!

Thanks,
G.

**Comment by marchbold** [comment]
I'll get this rolled out tomorrow but feel free to work with the above release.
