### ISSUE TITLE
Admob Mediation iOS: can't show rewarded Ads

### ISSUE THREAD

**Issue by TienThanh** [distriqt/ANE-IronSource#23]
I added Admob as mediation network, I tap on button to show rewarded ad, my game freeze!
I remove Admob mediation, everything work Ok!

Please check it!

- AIR SDK version: 33.1.1.444
- Device OS: 12
- Device version: iPhone 6, iPad Air 2
- Development IDE: Adobe Animate
- Development OS: MacOs 10.15.4

**Comment by marchbold** [comment]
Can you please post the logs from the device? Have you checked that the mediation adapter ane was correctly added along with the info additions?

**Comment by TienThanh** [comment]
> Can you please post the logs from the device? Have you checked that the mediation adapter ane was correctly added along with the info additions?

The admob mediation added successfully, I tested Ok with my iPhoneX (iOS 14).

**Comment by marchbold** [comment]
So it is working now?
