### ISSUE TITLE
No rewards for some ads

### ISSUE THREAD

**Issue by ldrlysysadmin** [distriqt/ANE-IronSource#24]
for an iOS build, we're using the latest distriqt ANEs (including IDFA, IronSource).  Sometimes, when onRewardedVideoAdRewarded is triggered, the data is empty.  (event.data = {})  This is not consistent, as it sometimes works and sometimes doesn't.
Under what circumstances can this occur?  And how can it be fixed?

**Comment by marchbold** [comment]
The data should always be empty. 

When isn't it?

**Comment by ldrlysysadmin** [comment]
For the ads that work, the data include placement ID, placement name, reward name, and reward amount.

**Comment by marchbold** [comment]
I don't know how that is possible as we don't return that data currently. Are you using the ironsource ANE? 

I'll get this listed as an enhancement and get it into development.

**Comment by marchbold** [comment]
Can you try this build for me:

https://www.dropbox.com/s/5e9j537gkr4mo7t/com.distriqt.IronSource.v2.4.1.zip?dl=0

I've added a `PlacementInfo` object instance on the rewarded event.

**Comment by ldrlysysadmin** [comment]
Our test with the ANE you provided now shows the PlacementInfo object in the event data, though it's the only object in the event data.  The PlacementInfo object contains entries for RewardAmount, PlacementName, and RewardName with the correct values.

**Comment by marchbold** [comment]
What exactly are you expecting?

**Comment by ldrlysysadmin** [comment]
It is as expected.  Just wasn't sure if there was anything you wanted to try and have us test, as we can replicate the issue relatively easily at the moment.
We'll use the provided ANE.  Thanks.

**Comment by ldrlysysadmin** [comment]
One last request.  Can you add the placement ID to the PlacementInfo object?

**Comment by marchbold** [comment]
placement id doesn't seem to be available in the ios event currently. I'll see if we can add it to android.
