### ISSUE TITLE
Crash On Android

### ISSUE THREAD

**Issue by gilil12** [distriqt/ANE-IronSource#25]
Hi Michael,

I just updated pushwoosh ANE to their latest version(6.0.6) and I see lots of crashes on the google play console that related to AppLoving mediation.

I **don't** think that the error is due to IronSource AppLoving mediation ANE.
the only thing that changed with the problematic build is pushwoosh SDK.
but maybe you can point me to what can cause this kind of crash on pushwoosh SDK.

> java.lang.RuntimeException: 
>   at android.content.res.AssetManager.ensureOpenLocked (AssetManager.java:520)
>   at android.content.res.AssetManager.addAssetPathInternal (AssetManager.java:466)
>   at android.content.res.AssetManager.addAssetPathAsSharedLibrary (AssetManager.java:450)
>   at android.webkit.WebViewFactory.getProviderClass (WebViewFactory.java:412)
>   at android.webkit.WebViewFactory.getProvider (WebViewFactory.java:252)
>   at android.webkit.WebSettings.getDefaultUserAgent (WebSettings.java:1313)
>   at com.applovin.impl.sdk.aa.b (Unknown Source:15)
>   at com.applovin.impl.sdk.l.h (Unknown Source:259)
>   at com.applovin.impl.sdk.l.<init> (Unknown Source:33)
>   at com.applovin.impl.sdk.k.a (Unknown Source:158)
>   at com.applovin.sdk.AppLovinSdk.a (Unknown Source:105)
>   at com.applovin.sdk.AppLovinSdk.getInstance (Unknown Source:1)
>   at com.ironsource.adapters.applovin.AppLovinAdapter.initSdk (AppLovinAdapter.java:223)
>   at com.ironsource.adapters.applovin.AppLovinAdapter.access$200 (AppLovinAdapter.java:55)
>   at com.ironsource.adapters.applovin.AppLovinAdapter$2.run (AppLovinAdapter.java:319)
>   at android.os.Handler.handleCallback (Handler.java:914)
>   at android.os.Handler.dispatchMessage (Handler.java:100)
>   at android.os.Looper.loop (Looper.java:224)
>   at android.app.ActivityThread.main (ActivityThread.java:7551)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)

Your help will be very appreciated.

Thanks,
Gili

**Comment by marchbold** [comment]
Hi, We are just about to push an update out for this extension with the latest mediators. Might be worth trying that out tomorrow?
