### ISSUE TITLE
No ads available (Android)

### ISSUE THREAD

**Issue by ldrlysysadmin** [distriqt/ANE-IronSource#26]
I've integrated the latest ANEs and noticed that I'm not getting any rewarded video ads for Android.  A build with the pre-androidx ANEs shows rewarded video ads available.  The log entries (obtained using adb.exe in the AIR SDK) from validateIntegration do not appear to show any problems.
Is there anything I've done incorrectly?
What can I do to narrow down the source of the problem?

**Manifest additions (facebook ads are not enabled on the ironsource console):**

```xml
					<!-- IRONSOURCE -->
					<!-- Ironsource: Core -->
                    <activity           android:name="com.ironsource.sdk.controller.ControllerActivity"
                                        android:configChanges="orientation|screenSize"
                                        android:hardwareAccelerated="true" />
                    <activity           android:name="com.ironsource.sdk.controller.InterstitialActivity"
                                        android:configChanges="orientation|screenSize"
                                        android:hardwareAccelerated="true"
                                        android:theme="@android:style/Theme.Translucent" />
                    <activity           android:name="com.ironsource.sdk.controller.OpenUrlActivity"
                                        android:configChanges="orientation|screenSize"
                                        android:hardwareAccelerated="true"
                                        android:theme="@android:style/Theme.Translucent" />
                    <provider           android:name="com.ironsource.lifecycle.IronsourceLifecycleProvider"
                                        android:authorities="air.com.eastsidegamestudio.PFGrassRoots.IronsourceLifecycleProvider" />

                    <!-- Ironsource: Facebook -->
                    <activity           android:name="com.facebook.ads.InterstitialAdActivity"
                                        android:hardwareAccelerated="true"
                                        android:configChanges="keyboardHidden|orientation|screenSize" />
                    <activity           android:name="com.facebook.ads.AudienceNetworkActivity"
                                        android:hardwareAccelerated="true"
                                        android:configChanges="keyboardHidden|orientation|screenSize" />
                    <provider           android:name="com.facebook.ads.AudienceNetworkContentProvider"
                                        android:authorities="air.com.eastsidegamestudio.PFGrassRoots.AudienceNetworkContentProvider"
                                        android:exported="false" />

```

**Log Excerpt for New ANEs:**

```
05-14 11:56:11.026  9973  9973 I IntegrationHelper: Verifying Integration:
05-14 11:56:11.026  9973  9973 I IntegrationHelper: *** Permissions ***
05-14 11:56:11.027  9973  9973 I IntegrationHelper: android.permission.INTERNET - VERIFIED
05-14 11:56:11.027  9973  9973 I IntegrationHelper: android.permission.ACCESS_NETWORK_STATE - VERIFIED
05-14 11:56:11.027  9973  9973 I IntegrationHelper: --------------- Facebook --------------
05-14 11:56:11.028  9973  9973 I IntegrationHelper: Adapter 4.3.26 - VERIFIED
05-14 11:56:11.028  9973  9973 I IntegrationHelper: Adapter - VERIFIED
05-14 11:56:11.028  9973  9973 I IntegrationHelper: SDK Version - 6.4.0
05-14 11:56:11.028  9973  9973 I IntegrationHelper: *** Activities ***
05-14 11:56:11.028  9973  9973 I IntegrationHelper: com.facebook.ads.AudienceNetworkActivity - VERIFIED
05-14 11:56:11.067  9973  9973 I IntegrationHelper: >>>> Facebook - VERIFIED
05-14 11:56:11.067  9973  9973 I IntegrationHelper: --------------- IronSource  --------------
05-14 11:56:11.068  9973  9973 I IntegrationHelper: Adapter 7.1.5.1 - VERIFIED
05-14 11:56:11.068  9973  9973 I IntegrationHelper: SDK Version - 5.99
05-14 11:56:11.068  9973  9973 I IntegrationHelper: *** Activities ***
05-14 11:56:11.069  9973  9973 I IntegrationHelper: com.ironsource.sdk.controller.ControllerActivity - VERIFIED
05-14 11:56:11.069  9973  9973 I IntegrationHelper: com.ironsource.sdk.controller.InterstitialActivity - VERIFIED
05-14 11:56:11.071  9973  9973 I IntegrationHelper: com.ironsource.sdk.controller.OpenUrlActivity - VERIFIED
05-14 11:56:11.108  9973  9973 I IntegrationHelper: *** Content Providers ***
05-14 11:56:11.109  9973  9973 D IntegrationHelper: com.ironsource.lifecycle.IronsourceLifecycleProvider- VERIFIED
05-14 11:56:11.109  9973  9973 I IntegrationHelper: >>>> IronSource - VERIFIED

05-14 11:57:01.182  9973  9973 D com.distriqt.IronSource: IronSourceController::isRewardedVideoAvailable()
05-14 11:57:01.182  9973  9973 I ironSourceSDK: API: RewardedVideoManager:isRewardedVideoAvailable()
05-14 11:57:01.182  9973  9973 I ironSourceSDK: API: isRewardedVideoAvailable():false
05-14 11:57:01.182  9973  9973 I air.com.eastsidegamestudio.PFGrassRoots: isAdAvailable - provider = [IronSourceAdProvider]
05-14 11:57:01.182  9973  9973 I air.com.eastsidegamestudio.PFGrassRoots: adAvailable = false
05-14 11:57:01.183  9973 12375 V ironSourceSDK: EVENT: {"eventId":1102
05-14 11:57:01.183  9973 12375 V ironSourceSDK: EVENT: "timestamp":1621018621182
05-14 11:57:01.183  9973 12375 V ironSourceSDK: EVENT: "provider":"Mediation"
05-14 11:57:01.183  9973 12375 V ironSourceSDK: EVENT: "eventSessionId":"55ea0132-acf2-41cf-82e7-325bf7e7ae87"
05-14 11:57:01.183  9973 12375 V ironSourceSDK: EVENT: "connectionType":"none"
05-14 11:57:01.183  9973 12375 V ironSourceSDK: EVENT: "sessionDepth":1}


**Log Excerpt for Old ANEs:**
05-14 15:02:47.563 25973 25973 I IntegrationHelper: Verifying Integration:
05-14 15:02:47.563 25973 25973 I IntegrationHelper: *** Permissions ***
05-14 15:02:47.563 25973 25973 I IntegrationHelper: android.permission.INTERNET - VERIFIED
05-14 15:02:47.563 25973 25973 I IntegrationHelper: android.permission.ACCESS_NETWORK_STATE - VERIFIED
05-14 15:02:47.563 25973 25973 I IntegrationHelper: --------------- Facebook --------------
05-14 15:02:47.564 25973 25973 I IntegrationHelper: Adapter 4.3.7 - VERIFIED
05-14 15:02:47.564 25973 25973 I IntegrationHelper: Adapter - VERIFIED
05-14 15:02:47.564 25973 25973 I IntegrationHelper: SDK Version - 5.6.0
05-14 15:02:47.564 25973 25973 I IntegrationHelper: *** Activities ***
05-14 15:02:47.564 25973 25973 I IntegrationHelper: com.facebook.ads.AudienceNetworkActivity - VERIFIED
05-14 15:02:47.564 25973 25973 I IntegrationHelper: com.facebook.ads.internal.ipc.RemoteANActivity - VERIFIED
05-14 15:02:47.564 25973 25973 I IntegrationHelper: *** Services ***
05-14 15:02:47.565 25973 25973 I IntegrationHelper: com.facebook.ads.internal.ipc.AdsProcessPriorityService - VERIFIED
05-14 15:02:47.565 25973 25973 I IntegrationHelper: com.facebook.ads.internal.ipc.AdsMessengerService - VERIFIED
05-14 15:02:47.565 25973 25973 I IntegrationHelper: >>>> Facebook - VERIFIED
05-14 15:02:47.565 25973 25973 I IntegrationHelper: --------------- IronSource  --------------
05-14 15:02:47.566 25973 25973 I IntegrationHelper: Adapter 6.10.2 - VERIFIED
05-14 15:02:47.566 25973 25973 I IntegrationHelper: SDK Version - 5.70
05-14 15:02:47.566 25973 25973 I IntegrationHelper: *** Activities ***
05-14 15:02:47.566 25973 25973 I IntegrationHelper: com.ironsource.sdk.controller.ControllerActivity - VERIFIED
05-14 15:02:47.567 25973 25973 I IntegrationHelper: com.ironsource.sdk.controller.InterstitialActivity - VERIFIED
05-14 15:02:47.567 25973 25973 I IntegrationHelper: com.ironsource.sdk.controller.OpenUrlActivity - VERIFIED
05-14 15:02:47.567 25973 25973 I IntegrationHelper: >>>> IronSource - VERIFIED

05-14 15:03:25.865 25973 25973 I air.com.eastsidegamestudio.PFGrassRoots: isAdAvailable - provider = [IronSourceAdProvider]
05-14 15:03:25.865 25973 25973 I air.com.eastsidegamestudio.PFGrassRoots: adAvailable = true
```

**Comment by marchbold** [comment]
Apologies I missed this question, did you resolve the issue?

**Comment by ldrlysysadmin** [comment]
Unfortunately not.  As the integration verification seems fine and there are no errors that I can see, I'm not sure what can be done to further narrow down the problem.

**Comment by marchbold** [comment]
Are you getting other ad types, just not rewarded?

**Comment by ldrlysysadmin** [comment]
Our app currently only implements rewarded ads.  (We don't have any interstitial ads or banner ads.)

**Comment by marchbold** [comment]
Have you checked with IronSource to make sure your account is approved? We have had issues with clients where their account seemed valid but was yet to be "made live" by IronSource.

**Comment by ldrlysysadmin** [comment]
The app has been live for years and we've been using IronSource for a long time as well.  The ads on the live game work.  Development builds using the old ANEs (pre-androidx) also work.
The main differences between the previous build and the latest build are:
- New build uses Java 8.112 whereas the old build used Java 7 (the app uses a 1024-bit signing key)
- New build uses the latest distriqt ANEs (live game/previous build use the distriqt ANEs prior to the androidx migration)

**Comment by marchbold** [comment]
What version of AIR are you using now? And what android api version are you targetting?

**Comment by ldrlysysadmin** [comment]
AIR 33.1.1.476
Target SDK 29

**Comment by marchbold** [comment]
Hmm, okay, we are definitely serving ads in our apps with a similar environment. Can you post the complete logs from your device, perhaps there's something else missing or another error that we can spot?

**Comment by ldrlysysadmin** [comment]
Here are a new set of logs.  I rebuilt the version with the old ANEs to ensure that it's built on the same machine, same AIR version, and same Java version as the new build.  (No difference in the results - no rewarded ads available on the build with new ANEs, ads available on the build with old ANEs.)
logs were created using the command:
  adb logcat -d -b main -b system -b events -v time > output_file.txt

[bfgr_log_old_ANEs.txt](https://github.com/distriqt/ANE-IronSource/files/6757065/bfgr_log_old_ANEs.txt)
[bfgr_log_new_ANEs.txt](https://github.com/distriqt/ANE-IronSource/files/6757066/bfgr_log_new_ANEs.txt)

**Comment by marchbold** [comment]
Can you try calling init like the below:

```as3
IronSource.instance.init( "YOUR_KEY",
		  [
			  "rewardedVideo",
			  IronSource.OFFERWALL
		  ]
);
```

**Comment by ldrlysysadmin** [comment]
changed the init from this:
	_ironSource.init(gameSettings["ironSourceAppKey"], [IronSource.REWARDED_VIDEO, IronSource.OFFERWALL]);
to this:
	_ironSource.init(gameSettings["ironSourceAppKey"], ["rewardedVideo", IronSource.OFFERWALL]);

No difference in the results.  Log shows the init changed from this:
    07-02 11:35:46.143 D/com.distriqt.IronSource(11511): IronSourceController::init( PFGRAPPID, [rewardedvideo,offerwall] )
to this:
    07-05 14:28:46.752 D/com.distriqt.IronSource(21035): IronSourceController::init( PFGRAPPID, [rewardedVideo,offerwall] )
(rewardedvideo --> rewardedVideo)
but still no rewarded video available:
07-05 14:28:59.906 I/ironSourceSDK: API(21035): RewardedVideoManager:isRewardedVideoAvailable()
07-05 14:28:59.906 I/ironSourceSDK: API(21035): isRewardedVideoAvailable():false
07-05 14:28:59.907 V/ironSourceSDK: EVENT(21035): {"eventId":1102
07-05 14:28:59.907 V/ironSourceSDK: EVENT(21035): "timestamp":1625520539906
07-05 14:28:59.907 V/ironSourceSDK: EVENT(21035): "provider":"Mediation"
07-05 14:28:59.907 V/ironSourceSDK: EVENT(21035): "eventSessionId":"145dc2ff-d1bf-473b-a9ad-5f9c57756a5a"
07-05 14:28:59.907 V/ironSourceSDK: EVENT(21035): "connectionType":"none"
07-05 14:28:59.907 V/ironSourceSDK: EVENT(21035): "sessionDepth":1}

**Comment by marchbold** [comment]
Can you list all the ANEs you are packaging? Just want to confirm you have all the dependencies:

https://docs.airnativeextensions.com/docs/ironsource/add-the-extension

Also can you make sure you are using the latest releases of those ANEs.

**Comment by ldrlysysadmin** [comment]
ANEs were last updated on June 28th.
Here's a list of all the ANEs used:
androidx.appcompat
androidx.browser
androidx.cardview
androidx.constraintlayout
androidx.core
androidx.multidex
androidx.recyclerview
androidx.vectordrawable
com.android.installreferrer
com.distriqt.Application
com.distriqt.ApplicationRater
com.distriqt.Bolts
com.distriqt.Core
com.distriqt.Dialog
com.distriqt.facebook.COre
com.distriqt.facebook.Login
com.distriqt.facebook.Share
com.distriqt.firebase.Crashlytics
com.distriqt.firebase.Performance
com.distriqt.firebase.RemoteConfig
com.distriqt.Firebase
com.distriqt.IDFA
com.distriqt.ironsource.FacebookAudience
com.distriqt.IronSource
com.distriqt.JobScheduler
com.distriqt.NetworkInfo
com.distriqt.Notifications
com.distriqt.playservices.Ads
com.distriqt.playservices.AdsIdentifier
com.distriqt.playservices.Base
com.distriqt.playservices.CloudMessaging
com.distriqt.PushNotifications.FCM
com.distriqt.square.okhttp3
com.google.android.datatransport
com.google.android.play
com.google.dagger
com.google.firebase.core
com.google.protobuflite

com.distriqt.CustomResources
and a couple custom ANEs (unrelated to ads)

**Comment by marchbold** [comment]
We have just updated the SDK to the latest again, could you try the latest build and see if you are still having issues?

**Comment by ldrlysysadmin** [comment]
I'm now getting a crash soon after validateIntegration is called.  To be precise, it is right after this line from the logs:
07-09 18:35:43.160 I/ironSourceSDK: INTERNAL(23041): ServerURL getCPVProvidersURL - parameters for url:
[Note: line is long so it's been truncated]
The error shown in the logs is this:
07-09 18:35:43.161 I/System.out(23041): IllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentException
[Note: again, the line is trunctated]

Log is attached.  Error occurs at line 3310 of the log.

Has there been a change to the initialization in the code or the manifest files required for the latest ANEs?

[bfgr_log_new_ANEs_v3.txt](https://github.com/distriqt/ANE-IronSource/files/6794488/bfgr_log_new_ANEs_v3.txt)

**Comment by marchbold** [comment]
I think we missed a dependency from the docs with this last update, try adding the `com.jetbrains.kotlin` dependency

- [com.jetbrains.kotlin](https://github.com/distriqt/ANE-AndroidSupport/raw/master/lib/com.jetbrains.kotlin.ane)

**Comment by ldrlysysadmin** [comment]
I think that last set of ANEs and the additional dependency may have fixed it.  We'll need to do more testing on our end to confirm.

**Comment by marchbold** [comment]
Glad to hear, let me know how you go.
