### ISSUE TITLE
setAdvertiserTrackingEnabled

### ISSUE THREAD

**Issue by gilil12** [distriqt/ANE-IronSource#27]
Hi ,

As from IOS 14 FAN requires to setAdvertiserTrackingEnabled to true to deliver ads.
can you expose the function to set it?

> OS 14+ Support 
If you are using Facebook adapter 4.1.7+, and building for iOS14+, FAN requires you to set the setAdvertiserTrackingEnabled flag. This allows you to inform Facebook whether to use the data to deliver personalized ads. If the flag is set to false FAN will not be able to deliver personalized ads. 

Thanks,
G.

**Comment by marchbold** [comment]
Will get this into our schedule when I can.
