### ISSUE TITLE
Access of undefined property IronSourceBannerSize

### ISSUE THREAD

**Issue by walddada** [distriqt/ANE-IronSource#29]
hi
This error occurred to me when I put the following code

IronSource.instance.loadBanner( IronSourceBannerSize.BANNER,  IronSource.POSITION_BOTTOM);

head of my project
		import com.distriqt.extension.ironsource.IronSource;
		import com.distriqt.extension.ironsource.events.RewardedVideoAdEvent;

**Comment by marchbold** [comment]
You need to import that class as well:

```as3
import com.distriqt.extension.ironsource.IronSourceBannerSize;
```

You can check the examples if you run into issues like this:

https://github.com/distriqt/ANE-IronSource/blob/master/example/ironsource/starling/src/com/distriqt/test/ironsource/IronSourceTests.as

Or the asdocs:

https://docs.airnativeextensions.com/asdocs/ironsource/

**Comment by walddada** [comment]
hello
thanks for your quickly help
I try this method
thanks again

**Comment by walddada** [comment]
I get this error :

1119: Access of possibly undefined property BANNER through a reference with
static type Class.

when I add banner class

IronSource.instance.init( IRONSRC_APP_KEY, [ IronSource.BANNER ] );

**Comment by walddada** [comment]
so

Well when I write the code
IronSource.instance.init( IRONSRC_APP_KEY, [ IronSource.

Well when I write the code

A small window appears with all the possible codes

[image: class_display.png]

that mean the BANNER not exit
