### ISSUE TITLE
Empty event.data  on callback function onRewardedVideoAvailabilityChanged

### ISSUE THREAD

**Issue by flarePL** [distriqt/ANE-IronSource#3]
Empty data 
on onRewardedVideoAvailabilityChanged

onRewardedVideoAvailabilityChanged 

 [DataEvent type="onRewardedVideoAvailabilityChanged" bubbles=false cancelable=false eventPhase=2 data=""]

##### Expected behaviour

data="true/false"

##### Actual behaviour

data=""

##### Environment 

- AIR SDK version: 32.0.0.103
- Device OS:  IOS, Android

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Please include some more information and the logs from the device so we can replicate.

**Comment by flarePL** [comment]
I don't use that ANE anymore.
