### ISSUE TITLE
IronSource.Admob and PushNotifications-FCM require different versions of android packages

### ISSUE THREAD

**Issue by mrfrasier** [distriqt/ANE-IronSource#31]
I'm back haha. Now that the folder is cleared out and I'm trying to get ads rolling again, I've started to add in the adapters I need. When I try to install the admob adapter I get conflicts with PushNotifications-FCM -- I'm guessing AdMob needs an update?

##### Expected behaviour
Ironsource.admob to install from command "apm install com.distriqt.ironsource.AdMob"

##### Actual behaviour
Multiple conflicts cause a fatal error

##### Environment 

- AIR SDK version: 33.1.1.821
- Device OS:  iOS
- Device version: 
- Development IDE:  VS Code
- Development OS: Windows 10

##### Logs

⣾ Finding package : com.distriqt.ironsource.AdMob@latest
✓ Found package: com.distriqt.ironsource.AdMob@1.0.111  
⣽ Finding package : androidx.appcompat@1.2.0
✓ Found package: androidx.appcompat@1.2.0   
⣻ Finding package : com.google.code.gson@2.8.6
✓ Found package: com.google.code.gson@2.8.6   
⢿ Finding package : androidx.constraintlayout@1.1.3
✓ Found package: androidx.constraintlayout@1.1.3   
⡿ Finding package : androidx.room@2.2.6
✓ Found package: androidx.room@2.2.6   
⣟ Finding package : androidx.work@2.5.0
✓ Found package: androidx.work@2.5.0   
⣯ Finding package : com.distriqt.IronSource@3.2.3
✓ Found package: com.distriqt.IronSource@3.2.3   
⣷ Finding package : com.google.guava@1.0.17
✓ Found package: com.google.guava@1.0.17   
⣾ Finding package : com.distriqt.Core@6.4.3
✓ Found package: com.distriqt.Core@6.4.3   
⣽ Finding package : androidx.core@1.3.2
✓ Found package: androidx.core@1.3.2   
⣻ Finding package : com.distriqt.playservices.Base@17.5.1
✓ Found package: com.distriqt.playservices.Base@17.5.1   
⢿ Finding package : com.distriqt.playservices.Ads@20.2.0
✓ Found package: com.distriqt.playservices.Ads@20.2.0   
⡿ Finding package : com.jetbrains.kotlin@1.4.10
✓ Found package: com.jetbrains.kotlin@1.4.10   
CONFLICT :: fatal error : found [3] conflicting packages
CONFLICT :: androidx.constraintlayout
CONFLICT :: ├── 2.1.3 required by: com.distriqt.PushNotifications-FCM@11.0.0
CONFLICT :: └── 1.1.3 required by: com.distriqt.ironsource.AdMob@1.0.111
CONFLICT :: com.google.guava
CONFLICT :: ├── 31.0.1 required by: com.distriqt.PushNotifications-FCM@11.0.0
CONFLICT :: └── 1.0.17 required by: com.distriqt.ironsource.AdMob@1.0.111
CONFLICT :: com.distriqt.playservices.Base
CONFLICT :: ├── 18.0.1 required by: com.distriqt.IronSource@3.3.1
CONFLICT :: └── 17.5.1 required by: com.distriqt.IronSource@3.2.3

**Comment by marchbold** [comment]
Hi, We have an update in beta for this at the moment. Aiming to release shortly.

**Comment by mrfrasier** [comment]
Any chance I can jump in that?

**Comment by marchbold** [comment]
Actually finalising it right now, will have this out tomorrow.

**Comment by marchbold** [comment]
@mrfrasier I've just been rechecking the issue above, your issue actually seems to be that you have an old version in your project. 

Can you post your apm file?

**Comment by mrfrasier** [comment]
> 

Old version of ironsource or pushnotifications? Just sent you an email with the file

**Comment by marchbold** [comment]
Ironsource, your apm file looks fine, maybe try a cache refresh:
- delete `project-lock.apm` 
- delete `apm_packages` directory 
- run `apm install`

**Comment by mrfrasier** [comment]
OK, did the above, then ran apm install com.distriqt.ironsource.AdMob, and got the below:

> ✓ Found package: com.jetbrains.kotlin@1.4.10   
> CONFLICT :: fatal error : found [3] conflicting packages
> CONFLICT :: androidx.constraintlayout
> CONFLICT :: ├── 2.1.3 required by: com.distriqt.PushNotifications-FCM@11.0.0
> CONFLICT :: └── 1.1.3 required by: com.distriqt.ironsource.AdMob@1.0.111
> CONFLICT :: com.distriqt.playservices.Base
> CONFLICT :: ├── 18.0.1 required by: com.distriqt.IDFA@5.1.0
> CONFLICT :: └── 17.5.1 required by: com.distriqt.IronSource@3.2.3
> CONFLICT :: com.google.guava
> CONFLICT :: ├── 31.0.1 required by: com.distriqt.PushNotifications-FCM@11.0.0
> CONFLICT :: └── 1.0.17 required by: com.distriqt.ironsource.AdMob@1.0.111
> install ::

Will send you current apm file

**Comment by mrfrasier** [comment]
Anything else to try? If not, is there something I can do to manually override? Spent a bit of time getting things working with APM and would hate to revert back to manually downloading ANEs

**Comment by marchbold** [comment]
For some reason the admob extension in apm hasn't been updated to the latest. Something must have failed in our deployment process. 

You can see the latest release here is v1.0.112

https://github.com/distriqt/ANE-IronSource/releases

but apm looks to be installing  1.0.111.

I'm looking into it and will resolve it asap.

**Comment by marchbold** [comment]
Okay, I've found the issue in our deployment process and have resolved it. You should now be able to access the latest version. 

Let me know if you are still having issues.

**Comment by mrfrasier** [comment]
Much thanks, that seems to have resolved things!

**Comment by marchbold** [comment]
Thanks for confirming and identifying the issue.

**Comment by aclipski** [comment]
Hi,

I'm running into a similar problem with the current version of the Admob adapter. Here is my output:

```
apm install com.distriqt.ironsource.AdMob
✓ Found package: com.distriqt.ironsource.AdMob@1.0.112  
✓ Found package: androidx.constraintlayout@2.1.301 
✓ Found package: androidx.room@2.3.1   
✓ Found package: androidx.work@2.7.1   
✓ Found package: com.google.code.gson@2.8.601 
✓ Found package: com.google.guava@31.0.101 
✓ Found package: com.distriqt.IronSource@3.3.1   
✓ Found package: com.distriqt.playservices.Base@18.0.101 
✓ Found package: com.distriqt.playservices.Ads@20.5.1   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.playservices.Ads
CONFLICT :: ├── 21.0.0 required by: com.distriqt.IronSource@3.4.0
CONFLICT :: └── 20.5.1 required by: com.distriqt.IronSource@3.3.1
install :: 
```

I already have the 3.4.0 IronSource adapter installed, do I need to downgrade it in order to install Admob?

Thanks!

**Comment by marchbold** [comment]
Could you start a new issue with this and we'll look into it.
