### ISSUE TITLE
Latest IronSource.Admob requires out-of-date version of IronSource

### ISSUE THREAD

**Issue by aclipski** [distriqt/ANE-IronSource#32]
I installed the latest version of com.distriqt.IronSource via apm (version 3.4.0), then tried to install IronSource.Admob via apm, which appears to require version 3.3.1 com.distriqt.IronSource, which in turn requires a different version of com.distriqt.playservices.Ads, causing an error.

##### Expected behaviour

Installing latest version of Admob via apm should succeed with the latest version of IronSource already installed

##### Actual behaviour

A fatal error occurs during installation and the installation fails

##### Environment 

- AIR SDK version: 33.1.1.889
- Device OS: iOS/Android
- Device version: 
- Development IDE: IntelliJ IDEA
- Development OS: Mac OS Monterey

##### Logs

```
apm install com.distriqt.ironsource.AdMob
✓ Found package: com.distriqt.ironsource.AdMob@1.0.112  
✓ Found package: androidx.constraintlayout@2.1.301 
✓ Found package: androidx.room@2.3.1   
✓ Found package: androidx.work@2.7.1   
✓ Found package: com.google.code.gson@2.8.601 
✓ Found package: com.google.guava@31.0.101 
✓ Found package: com.distriqt.IronSource@3.3.1   
✓ Found package: com.distriqt.playservices.Base@18.0.101 
✓ Found package: com.distriqt.playservices.Ads@20.5.1   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.playservices.Ads
CONFLICT :: ├── 21.0.0 required by: com.distriqt.IronSource@3.4.0
CONFLICT :: └── 20.5.1 required by: com.distriqt.IronSource@3.3.1
install :: 
```

**Comment by marchbold** [comment]
Will look into this as soon as I can.

**Comment by marchbold** [comment]
Let me know if you have any issues with the latest release.
