### ISSUE TITLE
SetMetaData Function

### ISSUE THREAD

**Issue by neutronized** [distriqt/ANE-IronSource#34]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this template and ask your question.

##### Expected behaviour
My game app is primarily directed at children so I should prevent access to the Android Advertising ID (AAID) otherwise my app is rejected by Google Play as not compliant.

IronSource provices a procedure to prevent access to the AAID at the following link (see Google Play Families policy):
https://developers.is.com/ironsource-mobile/android/regulation-advanced-settings/#step-3

I should call the following functions before initializing IronSource,
IronSource.SetMetaData("is_deviceid_optout","true");
IronSource.SetMetaData("is_child_directed","true");

##### Actual behaviour
Infortunately the IronSource ANE doesn't seem to provide the SetMetaData function call, unless I'm missing something?
Is there any way to opt out from accessing the AAID using this Ane?

##### Environment 

- AIR SDK version: 33.1.1.929
- Device OS: Android
- Device version: any
- Development IDE: Adobe Animator
- Development OS: Windows 10

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
We haven't implemented that function as yet. I'll get it into our schedule but can't guarantee when we'll get to it with this free extension.

**Comment by neutronized** [comment]
Thanks for your reply and for getting this into your schedule.

Google has been contacting developers because of apps not being compliant with Google Play Policies due to the AAID related to this SetMetaData function (please see attached image). Google is also giving a time limit of 60 days to solve such issue or the app will be removed from Google Play.

![issue](https://user-images.githubusercontent.com/1921185/192977533-7d4a500e-c6e3-47fb-bd9d-14730dda0ab1.jpg)

**Comment by marchbold** [comment]
I've managed to find some time to add this last night. 

Will roll out the update today. 

Cheers

**Comment by marchbold** [comment]
Let me know if you have any issues with the update.

**Comment by neutronized** [comment]
Hey, many thanks. No issues so far, was able to use the new functions and submit to Google Play Console without any warnings.
