### ISSUE TITLE
iOS Tapjoy crashes  ISTapjoyAdapter.m line 63 -[ISTapjoyAdapter .cxx_destruct]

### ISSUE THREAD

**Issue by ichark** [distriqt/ANE-IronSource#36]
The crash count increased after we added "com.distriqt.ironsource.Tapjoy.ane".
Here is a log message from Google Crashlytics:

##### Logs

**com.apple.root.utility-qos**
0  libsystem_kernel.dylib         0x34ec fsync + 8
1  Foundation                     0x3d6c0 _NSWriteDataToFileWithExtendedAttributes + 696
2  Foundation                     0xfb32c -[NSArray(NSArray) writeToFile:atomically:] + 172
3  Christmas Sweeper 3            0x742a40 -[ISTapjoyAdapter .cxx_destruct] + 63 (ISTapjoyAdapter.m:63)
4  Christmas Sweeper 3            0x740428 -[ISTapjoyAdapter .cxx_destruct] + 63 (ISTapjoyAdapter.m:63)
5  Christmas Sweeper 3            0x73fd88 -[ISTapjoyAdapter .cxx_destruct] + 63 (ISTapjoyAdapter.m:63)
6  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
8  libdispatch.dylib              0x15280 _dispatch_root_queue_drain + 680
9  libdispatch.dylib              0x1596c _dispatch_worker_thread2 + 164
10 libsystem_pthread.dylib        0x1080 _pthread_wqthread + 228
11 libsystem_pthread.dylib        0xe5c start_wqthread + 8

**com.ironsrc.sdkapi.queue**
0  libsystem_kernel.dylib         0x41a0 getattrlistbulk + 8
1  CoreServicesInternal           0x9c68 NextEntryFromParent + 184
2  CoreServicesInternal           0x9054 DirEnumRead + 388
3  CoreServicesInternal           0x8860 _GetDirectoryURLs(_CFURLEnumerator*) + 312
4  CoreServicesInternal           0x205c _URLEnumeratorGetNextURL + 140
5  Foundation                     0x51478 -[NSURLDirectoryEnumerator nextObject] + 92
6  CoreFoundation                 0x45214 -[NSEnumerator countByEnumeratingWithState:objects:count:] + 64
7  Christmas Sweeper 3            0xaa998c -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
8  Christmas Sweeper 3            0xa9ff64 -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
9  Christmas Sweeper 3            0xaa0048 -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
10 Christmas Sweeper 3            0xa939e0 -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
11 Christmas Sweeper 3            0xab2aa0 -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
12 Christmas Sweeper 3            0xab2f2c -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
13 Christmas Sweeper 3            0xab269c -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
14 Christmas Sweeper 3            0xa8745c -[SSWVMessageFunction .cxx_destruct] + 11 (SSWVMessageFunction.m:11)
15 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
16 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
17 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
18 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
19 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
20 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
21 libsystem_pthread.dylib        0xe5c start_wqthread + 8

##### Environment 
AIR SDK version: AIR 33.1.1.889
Device OS: Version:15.6.1

**Comment by marchbold** [comment]
Is there any more information on which thread caused the crash or the actual fault? All of that looks like it's internal to the ironsource sdk / adapter so worth reporting anything you find to ironsource.
