### ISSUE TITLE
Xcode 14 build tools AIR SDK update

### ISSUE THREAD

**Issue by mrfrasier** [distriqt/ANE-IronSource#43]
This appears to be the last thing blocking apm on my end

CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.2 required by: com.distriqt.Application@6.12.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.IronSource@3.5.2

Thanks!

**Comment by marchbold** [comment]
Ironsource was updated last week to 3.6.0 which should resolve this issue.

**Comment by mrfrasier** [comment]
> Ironsource was updated last week to 3.6.0 which should resolve this issue.

So it looks like the error is misleading. IronSource does install and update just fine. It's when I go to add the AdMob ANE:

apm install com.distriqt.ironsource.AdMob

**Comment by marchbold** [comment]
Ah, right, I'll double check all the mediators again. Which version of the mediator is it trying to install?

**Comment by mrfrasier** [comment]
> Ah, right, I'll double check all the mediators again. Which version of the mediator is it trying to install?

It looks like 1.2.0 based on this

⣾ Finding package : com.distriqt.ironsource.AdMob@latest
✓ Found package: com.distriqt.ironsource.AdMob@1.2.0

**Comment by marchbold** [comment]
I've updated the mediators, let me know if you are still having this issue.

**Comment by mrfrasier** [comment]
Looks to be good to go! And with that, all my conflicts are now resolved :) 

Thanks ma!
