### ISSUE TITLE
Some ios devices are not playing sound after video ad finished

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-IronSource#47]
In some iOS devices after the video ends, the game sounds stops working
I need to deactivate and activate and then the sounds returns to normal
any idea?

**Comment by marchbold** [comment]
Probably would need more information here before I can provide any suggestions. How are you playing music etc, what are you doing on deactivate/activate, what ios versions are affected?

**Comment by shaymolho** [comment]
I'm not getting deactivate/activate events when i play videos

**Comment by shaymolho** [comment]
and if I change the volume of the device the sounds return to normal

**Comment by shaymolho** [comment]
it looks like the problem is more severe 
when using the iron source sdk together with latest volume ANE (v3.2.0 )
on 
iphone max pro 12
ios 16.4
we don't hear sound at all even not related to video (upon login to the game)

i solved this problem by removing
        
        
        

and downgrading volume ANE to v3.1.16
I'm not sure which of the two solved or maybe only a combination of them I will check later and update more

**Comment by skyline7762** [comment]
I have same problem. 
It started happening with new SDK from 50.2.2.2.
Only on iOS.

**Comment by shaymolho** [comment]
@skyline7762 where do u see v50.2.2? in the [release page](https://github.com/distriqt/ANE-IronSource/releases) i only see version
v2.15.X for example

**Comment by skyline7762** [comment]
Adobe Air SDK :)
With 50.2.1 i do not have this problem.

**Comment by shaymolho** [comment]
for me it happens on air 33.1.1.935

**Comment by marchbold** [comment]
Hi, We can't replicate this behaviour so will need some more information about how you play music/sound in order to reproduce and debug this issue.

**Comment by skyline7762** [comment]
The sound seems to come back, but with a greater delay than before.

**Comment by marchbold** [comment]
This must be something internal to the ironsource sdk, if you can get me some more details I can try reporting it to ironsource , otherwise not a lot we can do if we can't replicate it. Cheers

**Comment by shaymolho** [comment]
what details more do you need? ios logs?

**Comment by marchbold** [comment]
Yeah the logs would be a good starting point but really any information you can provide, ideally a minimal example with a simple sound playback replicating the issue. And details on which network (if using mediation) is causing the issue.

**Comment by shaymolho** [comment]
hi @marchbold I'm attaching ios device logs for the issue that sound is stopped after a video is played
[sound-stop-after-video-ios-device-logs.zip](https://github.com/distriqt/ANE-IronSource/files/11365604/sound-stop-after-video-ios-device-logs.zip)

**Comment by marchbold** [comment]
Could you tell me how you are playing sounds, is this purely through the flash media API? Do you have access to the MediaPlayer extension to see if sound played through there is affected as well?

**Comment by skyline7762** [comment]
Yes, I play music/sounds only through the Flash Media API.
You have to hide and return to the app again for the sound to come back.

**Comment by marchbold** [comment]
Yeah we have experienced something similar, we are trying to isolate the cause but have a feeling it might be due to some changes in AIR as we can still play sounds/music using the MediaPlayer extension in the same scenario.

**Comment by shaymolho** [comment]
@marchbold please update us if we can help more to pinpoint the problem

**Comment by marchbold** [comment]
If you can identify exactly which network is causing the issue and provide a test app that replicates it for Harman that would be helpful. We are having issues producing a test that replicates the issue every time, seems to only be certain ads or networks that cause it. I have a feeling it's something to do with the activity lifecycle events it goes through but haven't nailed down the exact case yet.

**Comment by skyline7762** [comment]
You can check this out on our application from AppStore.
https://apps.apple.com/us/app/glitty-color-glitter-art/id1514230501

**Comment by shaymolho** [comment]
@marchbold any update on this?

**Comment by marchbold** [comment]
As far as we can tell this is an ironsource issue. Will update the SDK soon and see if that resolves the issue.

**Comment by alexSerebriakovMoonmana** [comment]
I have the same issue, sound dissapears after an ad video, if you change volume, sound comes back, also, minimizing and maximizing the app helps

**Comment by alexSerebriakovMoonmana** [comment]
It resolved when i updated air sdk to 50.2.4.4 version

**Comment by marchbold** [comment]
@alexSerebriakovMoonmana Thanks for letting us know.
