### ISSUE TITLE
com.google.code.gson ane v 2.8.901 is with air 50.2 namespace

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-IronSource#49]
this break if not yet on air 50.2
as
com.google.code.gson ane v 2.8.900
is with air 33.1

Would be great if you could downgrade the namepsace back to 33.1 and upload a new ANE

**Comment by marchbold** [comment]
Unfortunately we are using the new build mechanism in AIR 50.2 now. 

AIR 33.1 doesn't support the latest gson version.

**Comment by shaymolho** [comment]
will upgrade to air 50. thx
