### ISSUE TITLE
ANE doesn't work

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-IronSource#5]
Hi Michael,

OK after integrating the ANE and test it,
we saw that the ANE doesn't work.

The API is the same as IronSource's ANE so there was no need in the code.
Just changing the ANE and the package in our code.

Doing so and running the app,
we got only one event: "onRewardedVideoAvailabilityChanged"
with Value = FALSE meaning there is no videos,
and the state never changed...
Even if we ignore the state and call show rewarded video:
`IronSource.instance.showRewardedVideo();`
Nothing happens.

Switching back to IronSource's ANE (it does work on Android),
We see that everything works as expected :(

what to do next?

Shay

**Comment by marchbold** [comment]
As I said, this is mainly developed for our needs and it's working for us. 

If you can post some more information including the logs from the device and android versions you've tried  I'll look into it when I get a chance.

**Comment by flarePL** [comment]
@shaymolho  when you open new issue, make sure there is no other same as yours 
https://github.com/distriqt/ANE-IronSource/issues/3
