### ISSUE TITLE
No bids from Facebook Audience (Meta) mediation

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-IronSource#51]
Using latest version v2.16.0 we are not getting any bids from facebook. We double checked our configuration and everything looks ok.
In facebook dashboard we see the following error:

> A bidder token is missing from bid requests

![image](https://github.com/distriqt/ANE-IronSource/assets/6802402/f3277456-9530-4901-8725-fd37b2a3cb97)
we initialize facebook like this:

```
FacebookAudience.instance.adSettings.setDataProcessingOptions([]);
FacebookAudience.instance.adSettings.setAdvertiserTrackingEnabled(true);
```

please advise on this

**Comment by shaymolho** [comment]
@marchbold plz advise

**Comment by marchbold** [comment]
Have you contacted ironsource to see if they know the reason for this behaviour?

**Comment by shaymolho** [comment]
ironsource checked our account with facebook mediation integration and ironsource said they see bid requests from our app to facebook
so the problem is around the SDK

**Comment by marchbold** [comment]
Which SDK do you believe the problem to be in?

**Comment by shaymolho** [comment]
`com.distriqt.ironsource.FacebookAudience`
the problem happens on android
we didn't test ios

**Comment by marchbold** [comment]
What did they say the issue was? There isn't a lot of implementation in the mediation adapters just inclusion of the sdk.

**Comment by shaymolho** [comment]
Hi @marchbold,

We worked with Ironsource support and this is the response they sent us:

```
We were able to receive a test ad from Facebook bidding today using your app key in our test app. So it appears things are configured correctly.

What I would suggest is updating to the latest version of the ironSource SDK and the latest version of all adapters to rule out any issue there. Also, are you using a third party plugin rather than our official one?

It may also be worth contacting Facebook to see if they can share why they aren't responding to the bid requests.

Best,
Kieran
Staff Integrations Engineer
```


So as they write, they tested our configuration with a test application and the facebook bid worked correctly.
More over, i'll add that other ad mediations we integrated work without any issue (AdMob, Unity Ads, Ad colony, Tapjoy all works well on production).

So it seems there is something missing in the facebok audience mediation, that prevents it from sending the 'bid token' that is needed.

I think that the problem is either in the Ironsource ANE or the FacebookAudience ANE.

Does it work on your side?

Thanks,
Shay

**Comment by marchbold** [comment]
I don't have any active applications using facebook currently. I'll try and find some time to update this to the latest sdk and see if that resolves the issue.

**Comment by shaymolho** [comment]
Hi Michael,

Do you have an ETA for update of the SDK or other solution for this issue?

We currently can't work with Facebook Audience Network as we need it.

Thanks,
Shay

**Comment by marchbold** [comment]
No ETA currently, I try to update this extension in my spare time, which I don't have a lot of right now. But will see how I go over the next fortnight.
