### ISSUE TITLE
Impression level revenue integration

### ISSUE THREAD

**Issue by ichark** [distriqt/ANE-IronSource#52]
Good day.
Could you please help and add the ability to receive the 
"onImpressionDataDidSucceed" event from IronSource 
as described in this example:
 https://developers.is.com/ironsource-mobile/air/ad-revenue-measurement-integration-adobe-air/

**Comment by marchbold** [comment]
Hi, Will look into it for the next release.

**Comment by ichark** [comment]
Hi, have a nice day. Could you have any news when planned next update?

**Comment by marchbold** [comment]
Hi, Currently looking at an update in September for this extension.
