### ISSUE TITLE
iOS Unity & Chartboost mediations

### ISSUE THREAD

**Issue by sweetnitro** [distriqt/ANE-IronSource#54]
Hello,

When starting an app with Unity or Chartboost on iOS, it crashes with something like this in the crash log:
DYDL, symbol XXXX not found, expect in /System/Library/Framworks/Foundation.framework/Foundation.

We're building with 50.2.2.6 but also tried 50.2.2.5. Our mac (to build it) and xcode are fully up to date.

test device: iphone X with iOS version 14.6

Could it be related to this issue? https://github.com/airsdk/Adobe-Runtime-Support/issues/2685
Because I've noticed these 2 ANEs are using swift.

Thanks!

**Comment by mateo-kozomara** [comment]
@marchbold did this ANE work in your test environment?

**Comment by marchbold** [comment]
We don't have any issues packaging these, but we have encountered some runtime issues that we are investigating. Issue may be related but I'm not sure currently.

**Comment by mateo-kozomara** [comment]
Thanks. Yes, im also having the exactly same runtime issue with UnitySDK.

**Comment by marchbold** [comment]
Oh right, yeah we have been advising against using the platformsdk option lately, seems to have issues with a lot of things currently, and yeah swift libs is one of them.
