### ISSUE TITLE
Ironsource mediation RV ads not retrieving ads on new project

### ISSUE THREAD

**Issue by yvant** [distriqt/ANE-IronSource#57]
Hi,

I tried using mediation with AdMob on a first app (released on the store), and I can see it worked:

I did see the test ads, then the live ads on the game
I've seen on the console that some ads have been seen by players and that it generated some revenue, validating the process
My next step is to integrate this mediation to another game (live too), but it doesn't work:

When I use this second app App Key, I don't get ads in the game (onRewardedVideoAvailabilityChanged doesn't trigger)
However, when I use the first App Key on this second game, I can see ads in it
Can I send the logs by mail to see where it comes from?

**Comment by yvant** [comment]
Indeed this is what I thought since it's working with the other AppID, but I was wondering if it could come from something else. I've double checked the differences between the 2 games configurations, removed all testing devices, but I don't have any clue now.

**Comment by marchbold** [comment]
You might have to reach out to ironsource, we have had many occasions where an app id was disabled by ironsource for some unknown reason. Everything looked fine in the console but their backend had a flag that was blocking it.

**Comment by yvant** [comment]
Yes, in the end the issue came from IronSource and they were able to unlock the situation. Thanks for your support!
