### ISSUE TITLE
Missing documentation regarding ad networks

### ISSUE THREAD

**Issue by TheAnosmic** [distriqt/ANE-IronSource#6]
##### Expected behaviour
Documentation regarding which ad networks are supported and built-in in the ane and which are needed to be added as an adapter from IronSource

##### Actual behaviour
We are trying to add Vungle/Chartboost ane etc., but apple rejects our ipa.

##### Environment 

- AIR SDK version: 32.0.0.116
- Device OS: N/A
- Device version: N/A
- Development IDE: Adobe Animate
- Development OS: Windows

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
None are built into the ANE. You need to use the adapters from IronSource, we haven't needed to wrap these as the supplied versions have worked for us.
