### ISSUE TITLE
Need update version to support Google certified CMP

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-IronSource#60]
Dear Publishers
 
From January 16th, 2024, publishers and developers using Google's ad products will be required to use a Google certified CMP (Consent Management Platform) that integrates with the TCF 2.0 ([Transparency and Consent Framework](https://go.is.com/e/912171/ransparency-consent-framework-/93qrr/851486086/h/1enyaY30RbxjrX_1oy5qN-nYrI0_7hLjCEbGk5MDSlQ)) when serving ads to users in the European Economic Area or the UK. More information on Google's policy is available [here](https://go.is.com/e/912171/admob-answer-13554116-hl-en/93qrv/851486086/h/1enyaY30RbxjrX_1oy5qN-nYrI0_7hLjCEbGk5MDSlQ).
 
What you should do:
To support publishers that implement a TCF CMP, Tapjoy exposes a consent API in its SDK, which allows the publisher to share the user’s choice with the Tapjoy SDK.
 
1. Publishers using Google UMP and CMPs that support Google’s Additional Consent
If you use Google UMP (Google’s CMP), or other CMPs that support Google’s Additional Consent (Google’s solution for non-registered TCF vendors), complete the necessary configurations on the AdMob platform. Learn more here. If you are using other CMPs that are not Google UMP, please read the instructions of such CMPs on how to set the Google Additional Consent. Make sure that “ironSource Mobile” is included in Google’s Additional Consent. Set the[ consent API exposed by the Tapjoy SDK](https://go.is.com/e/912171/en-SDK-Privacy-Flags/93qry/851486086/h/1enyaY30RbxjrX_1oy5qN-nYrI0_7hLjCEbGk5MDSlQ) based on the consent value stored in the AC String for “ironSource Mobile”.

2. Publishers using other CMPs
If you are not using Google UMP, or other CMPs that support Google’s Additional Consent , you will need to set Tapjoy as a custom vendor based on the instructions from the CMP. Set the [consent API exposed by the Tapjoy SDK](https://go.is.com/e/912171/en-SDK-Privacy-Flags/93qry/851486086/h/1enyaY30RbxjrX_1oy5qN-nYrI0_7hLjCEbGk5MDSlQ) based on the consent value stored by the CMP for Tapjoy.

Please follow the instructions and reach out to your account partner with any questions.
 
 
The Tapjoy offerwall team

**Comment by marchbold** [comment]
I'll look into it when I get some time to update the ironsource extension. I'm just maintaining this one in my free time.

**Comment by marchbold** [comment]
Update rolling out today, could you let us know if you continue to see this issue with the update?

**Comment by Mintonist** [comment]
Thx!
