### ISSUE TITLE
iOS: App crashes when the Unity adapter is added

### ISSUE THREAD

**Issue by mrfrasier** [distriqt/ANE-IronSource#61]
## Problem Description

Using both AIR SDK 50.2.4.4 and 50.2.4.2 the app crashes in both dev and testflight modes on launch on an iPhone 14 running iOS 16.

Build worked previously with no issue. I determined this by checking the crash logs. I found mentions of Unity in there and so decided to try to remove it. Tried an APM update to see if there was a newer adapter, but I have the latest @ 4.8.1 according to APM

`{"imageOffset":9395088,"symbol":"+[UnityAds serviceProvider]","symbolLocation":32,"imageIndex":1},{"imageOffset":9394312,"symbol":"+[UnityAds setDebugMode:]","symbolLocation":32,"imageIndex":1},{"imageOffset":9922328,"symbol":"__53-[ISUnityAdsAdapter initSDKWithGameId:adapterConfig:]_block_invoke_2","symbolLocation":484,"imageIndex":1}`

I have tried downgrading to 4.8.0 to no avail. Removing the extension from the XML resolves the issue.

**Comment by marchbold** [comment]
Is there any more details on the crash at all? A crash log or more in the console logs?

**Comment by Mintonist** [comment]
I have app crash on Android with Unity mediation (after` IronSource.instance.init()` ). I try different combinations of mediations and exactly Unity is buggy(
AIR 50.2.4.4, Windows, Idea 2022, lastest ANEs

**Comment by marchbold** [comment]
@Mintonist Can you post the issue with Android in a separate thread and include the device logs

**Comment by marchbold** [comment]
Update rolling out today, could you let us know if you continue to see this issue with the update?

**Comment by mrfrasier** [comment]
Issue appears resolved!

**Comment by marchbold** [comment]
Great! Thanks for confirming.
