### ISSUE TITLE
IOS compile error after adding AdMob mediation

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-IronSource#62]
AIR50.2.4.4, Windows, all ANEs have the lastest version

I can build IOS app without errors if I use only IronSource ANE without mediation.

 But after adding AdMob mediation I get an error:

ld64: error: undefined symbol: _APMUserDataFieldEmailAddress >>> referenced by ...\\AppData\\Local\\Temp\\1ac0d126-11b7-4b87-bbad-daaaea8eec5a\FirebaseAnalytics.framework\FirebaseAnalytics(FIRAnalytics.o):(symbol +[FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:]+0x5c) >>> referenced by ...\\AppData\\Local\\Temp\\1ac0d126-11b7-4b87-bbad-daaaea8eec5a\FirebaseAnalytics.framework\FirebaseAnalytics(FIRAnalytics.o):(symbol +[FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:]+0x58)

My list of extensions:
```
 <extensions>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>com.distriqt.Application</extensionID>
        <extensionID>com.distriqt.InAppBilling</extensionID>
        <extensionID>com.distriqt.GameServices</extensionID>
        <extensionID>com.distriqt.PushNotifications</extensionID>
        <extensionID>com.distriqt.NetworkInfo</extensionID>
        <extensionID>com.distriqt.Share</extensionID>
        <extensionID>com.distriqt.ApplicationRater</extensionID>

        <extensionID>com.google.firebase.core</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>

        <extensionID>com.distriqt.IronSource</extensionID>
        <extensionID>com.distriqt.ironsource.AdMob</extensionID>
     </extensions>
```

P.S. All works fine for Android platform.

**Comment by marchbold** [comment]
I'd say this is related to the current linking issues in AIR on Windows. Have you tried a build on macOS?

**Comment by marchbold** [comment]
Unfortunately not all linking issues have been resolved . There are still many things that can't be done on Windows and likely will not be able to. Harman is looking into alternative solutions revolving around mac build systems.

**Comment by mrfrasier** [comment]
@Mintonist wonder if you're also using PushNotifications-FCM? Had the same issue and turned out it was a conflict between that and the admob mediation adapter. The latest update to the IronSource ANE sorted it out

**Comment by marchbold** [comment]
Worth trying the latest release here now as this should bring AdMob up to date.

**Comment by Mintonist** [comment]
@mrfrasier @marchbold Thanks! Now i can build IPA on Windows.
