### ISSUE TITLE
IOS. AppLovin. Invalid Bundle

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-IronSource#63]
AIR 50.2.4.4, Windows, Idea 2022, lastest ANEs

   ```
 <extensions>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>com.distriqt.Application</extensionID>
        <extensionID>com.distriqt.InAppBilling</extensionID>
        <extensionID>com.distriqt.GameServices</extensionID>
        <extensionID>com.distriqt.PushNotifications</extensionID>
        <extensionID>com.distriqt.NetworkInfo</extensionID>
        <extensionID>com.distriqt.Share</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>
        <extensionID>com.distriqt.ApplicationRater</extensionID>
        <extensionID>com.google.firebase.core</extensionID>

        <extensionID>com.distriqt.IronSource</extensionID>
        <extensionID>com.distriqt.ironsource.AppLovin</extensionID>
        <extensionID>com.distriqt.ironsource.Chartboost</extensionID>
        <extensionID>com.distriqt.ironsource.FacebookAudience</extensionID>
     </extensions>
```
I can create IPA without errors but I have error while deliver to AppStore:

> ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/ForestBounty.app/AppLovinSDKResources.bundle/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit."

**Comment by marchbold** [comment]
Please try building on macOS, I don't believe windows can handle these frameworks correctly any longer.

**Comment by Mintonist** [comment]
Do you have instruction for this? Easiest way to develop on Windows and build on Mac (Virtual machine). Seems I can share folder between guest and parent machine and call adt on project's folder?
Thanks!

**Comment by marchbold** [comment]
Unfortunately I don't have any instructions for this, we generally just use macos for developing ios applications as it's much easier to test and debug there. 

I believe the Harman team are working on a series of major improvements for this though, including automatically connecting to a macos machine to build from a windows machine, but this is still in development.
