### ISSUE TITLE
Unity mediation crash on Android

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-IronSource#64]
I have app crash on Android with Unity mediation (after IronSource.instance.init() ). I try different combinations of mediations and exactly Unity is buggy(
AIR 50.2.4.4, Windows, Idea 2022, lastest ANEs

[logcat.txt](https://github.com/distriqt/ANE-IronSource/files/14982070/logcat.txt)

**Comment by marchbold** [comment]
We have an update for ironsource and all these mediators in final stages of development. I'll get this out asap.

In the meantime, you could try adding the androidx.webview extension. Seems we missed that from the docs but it gets added when you use apm.

**Comment by Mintonist** [comment]
I can not find 'androidx.webview' in ANE-AndroidSupport-2.8.1
Where can I get it?

**Comment by marchbold** [comment]
Apologies I meant `androidx.webkit`

https://github.com/distriqt/ANE-AndroidSupport/raw/master/lib/androidx.webkit.ane

**Comment by marchbold** [comment]
Update rolling out today, could you let us know if you continue to see this issue with the update?

**Comment by marchbold** [comment]
I'll get that link updated, the correct link is:

https://github.com/distriqt/ANE-SquareLibs/raw/master/lib/com.distriqt.square.okhttp3.ane

Yes you'll need to add those assets.

As a general rule with all our extensions anything in the `assets/android` folder should be added to your android builds and anything in the `assets/ios` should be added to your ios builds. All at the root level.

**Comment by Mintonist** [comment]
Thanks!
