### ISSUE TITLE
IOS Submit error after update to IronSource ANE v.3.0

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-IronSource#65]
Hi!

AIR 50.2.5.1, Windows, Idea 2022

ERROR ITMS-90171: "Invalid bundle structure. The “ForestBounty.app/libIronSourceAdQuality.a” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle"

I know about problem with IOS build on Windows. But previous ANE version works

**Comment by marchbold** [comment]
Ah yes, this was a packaging issue on our side, I'll get it fixed today.
