### ISSUE TITLE
Failed to copy Adobe AIR native extension *AppLovin.ane* because the file was not found.

### ISSUE THREAD

**Issue by mrfrasier** [distriqt/ANE-IronSource#66]
Unsure if this is an APM thing but I'm only having issues with this one ANE.

Starting today, I can't quick compile and run in VS Code on Windows 11 because I get this error:

`Failed to copy Adobe AIR native extension from path: APP_PATH\.\ane\com.distriqt.ironsource.AppLovin.ane because the file was not found.`

 If I try to do an "update" on the ANE after deleting the file (which does exist btw) I get this error:

```
apm update com.distriqt.ironsource.AppLovin
⣯ Deploying package: com.distriqt.ironsource.AppLovin@12.3.100
E::ProcessQueue::Error #3012
⣷ Deploying package: com.distriqt.ironsource.AppLovin@12.3.100 ane
```

If I go to uninstall I get a similar error:

```
apm uninstall com.distriqt.ironsource.AppLovin
Uninstall package : com.distriqt.ironsource.AppLovin
⣾ Removing config for package : com.distriqt.ironsource.AppLovin
✓ Removed config for package : com.distriqt.ironsource.AppLovin 
⣽ Removing package : com.distriqt.ironsource.AppLovin
E::ProcessQueue::Error #3013
com.distriqt.ironsource.AppLovin :: Error #3013
```

To fix, I have to restart VS Code then run apm uninstall again to remove the ANE. Then the project runs just fine.

Apologies if this doesn't fall on you Michael, but was unsure if this was an issue with the AppLovin extension, APM or VSCode/Actionscript extension. Since you managed 2 of the 3, figured reporting to you would make the most sense.

Not urgent, AppLovin doesn't do much for us so removing it is fine, especially while testing on desktop. Just wanted to raise the issue.

**Comment by marchbold** [comment]
That looks like an issue with apm, could you log an issue in the apm repository and include the output from apm with the debug enabled: 

`apm -l d ...`
