### ISSUE TITLE
iOS Crash with Unity Ads at iOS: 15.x.x

### ISSUE THREAD

**Issue by ichark** [distriqt/ANE-IronSource#68]
Problem Description: 
App crashes after the call
```
IronSource.instance.init(adsProviderAppKey, [ IronSource.REWARDED_VIDEO, IronSource.INTERSTITIAL, IronSource.BANNER])
```
if set at IronSource mediation test UnityAds for this device.  
Tested with last ANE's installed by APM.  
Device  OS:  iPadOS 15.8.2
AIR SDK  50.2.4.5 
list of all use ANE's : 
[ane's.txt](https://github.com/distriqt/ANE-IronSource/files/15456639/ane.s.txt)
console log: 
[ipad.log](https://github.com/distriqt/ANE-IronSource/files/15456652/ipad.log)
crash log: 
[cs3_ios_b-2024-05-27-160357.log](https://github.com/distriqt/ANE-IronSource/files/15456666/cs3_ios_b-2024-05-27-160357.log)

**Comment by ichark** [comment]
I tried to update the AIR SDK to 51.0.1.1 but the app crashed with the same behavior.

**Comment by marchbold** [comment]
Please try the latest release, this should be resolved but let me know if you are still having issues.

**Comment by ichark** [comment]
Hi, @marchbold !

Our team has double-checked everything. We have updated all the ANEs and are using the latest version of AIR, 51.0.1.3. Unfortunately, the problem still persists on iOS devices with system version 15. The crash occurs when selecting UnityAds or UnityAds Bidding in the IronSource control panel.

**Comment by marchbold** [comment]
Hi, Yes we have been able to replicate this with the unityads sdk, AIR and iOS v15.8.x so seems to be something specific to that combination. We haven't been able to isolate the reason as yet but are working on it. Once we isolate the issue in our Adverts extension I'll port it across to this free extension.

**Comment by ichark** [comment]
Hello, @marchbold !
Could you please let us know if you were able to fix this issue in ANE-Adverts-Mediation?
Have you possibly planned an update for ANE-IronSource with the updated Unity SDK?
Our team is eagerly waiting for the update. Thank you. Have a great day.

**Comment by marchbold** [comment]
As this is a free extension we only update it when we have time. Feel free to [sponsor](https://github.com/sponsors/marchbold) us to help us continue maintaining this extension. 

We are looking into the admob mediator.

Cheers

**Comment by ichark** [comment]
Yes, of course! 
It's great that you're supporting this ANE. 
We hope our assistance will be helpful to you. We're looking forward to the upcoming update. 
Have a great day! ;)

**Comment by ichark** [comment]
Yes, of course! It's great that you're supporting this ANE. We hope our assistance will be helpful to you. We're looking forward to the upcoming update. Have a great day! :wink:

**Comment by marchbold** [comment]
Much appreciated! I'm working on the admob one currently and will get the ironsource one done next.

**Comment by marchbold** [comment]
I have an update rolling out today that resolves this issue. One important note though, you need to use the platformsdk option and provide a recent version of the iOS SDK. You can do this through your adt config with the AIR SDK Manager, via the command line or via the options in your IDE (depending on the IDE you are using). 

There seems to be an issue with the iOS stubs in the AIR SDK currently so providing the iOS SDK manually appears to be the only way around these crashes on iOS 15.x.
