### ISSUE TITLE
iOS Application freezes after init()

### ISSUE THREAD

**Issue by ichark** [distriqt/ANE-IronSource#69]
## Problem Description

iOS Application freezes after IronSource.instance.init().
The issue happens after adding the NativeWebView ANE extension.  
Used with the last versions of ANE's installed by APM.
AIR SDK 50.2.4.5
list of all use ANE's :
[ane's.txt](https://github.com/distriqt/ANE-IronSource/files/15471173/ane.s.txt)
console log:
[ipad.log](https://github.com/distriqt/ANE-IronSource/files/15471177/ipad.log)

## Steps to Reproduce

Just add a  "com.distriqt.NativeWebView" to the extensions list.  Application freezes throw 10 - 20 seconds  after the init the IronSource. 
Same behavior if use or not NativeWebView functions.

**Comment by marchbold** [comment]
This should be corrected in the latest release.
