### ISSUE TITLE
Documentation: setDynamicUserId not working / documentation missing

### ISSUE THREAD

**Issue by noamgat** [distriqt/ANE-IronSource#7]
Hi. 
In the normal IronSource SDK, they require the developer to call setUserID before initializing the plugin.
When porting it to this one (due to air 32 support), we kept the behaviour, but this does not seem to be working - the server-to-server callbacks we receive now contain the device / advertiser UDID and not our reported internal user IDs.
The documentation does not mention the usage of this. Could you elaborate on the correct usage of this?

**Comment by noamgat** [comment]
Perhaps setUserID must also be implemented?
https://developers.ironsrc.com/ironsource-mobile/android/advanced-settings/#step-1

**Comment by marchbold** [comment]
Will look into it when we can.

**Comment by noamgat** [comment]
Thanks. I see you marked it as enhancement. While I agree that adding setUserID is an enhancement, fixing setDynamicUserId (which is not working, after contacting IronSource support) would also do the trick for us.

**Comment by noamgat** [comment]
After speaking to Ironsource support, if an IronSource test device (configured via their portal) runs the setDynamicUserId call correctly, the following line should appear in the ADB logs:
API: IronSource: setting dynamicUserId to ___________
We have tried this and do not see the call in the logs, so it looks to be indeed not working.

**Comment by marchbold** [comment]
This will be resolved in the next build (see #8 for the beta)

**Comment by shaymolho** [comment]
so how to set the user id? i didn't find this in docs
@marchbold

**Comment by marchbold** [comment]
@shaymolho We haven't implemented that function as yet. Add a feature request as a separate issue and I'll look into it when I have time.
