### ISSUE TITLE
No mediation detected

### ISSUE THREAD

**Issue by ventr1x** [distriqt/ANE-IronSource#9]
Hi,

I know this ane is not officially supported but as it's currently the only way to get IronSrc with 64bit Android running, I tried it out a little.

Replacing the official IronSrc ane with this one results in IronSrc network test ads and no mediation being detected.
Is there something to be aware of? Or is the current github version simply not usable for us?

> 08-19 11:03:50.647 19490 19490 I IntegrationHelper: Adapter 6.8.2 - VERIFIED
> 08-19 11:03:50.647 19490 19490 I IntegrationHelper: *** Activities ***
> 08-19 11:03:50.649 19490 19490 I IntegrationHelper: com.ironsource.sdk.controller.ControllerActivity - VERIFIED
> 08-19 11:03:50.651 19490 19490 I IntegrationHelper: com.ironsource.sdk.controller.InterstitialActivity - VERIFIED
> 08-19 11:03:50.652 19490 19490 I IntegrationHelper: com.ironsource.sdk.controller.OpenUrlActivity - VERIFIED
> 08-19 11:03:50.652 19490 19490 I IntegrationHelper: >>>> IronSource - VERIFIED
> 08-19 11:03:50.652 19490 19490 I IntegrationHelper: --------------- AdColony --------------
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: >>>> AdColony - NOT VERIFIED
> 08-19 11:03:50.653 19490 19490 I IntegrationHelper: --------------- AppLovin --------------
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: >>>> AppLovin - NOT VERIFIED
> 08-19 11:03:50.653 19490 19490 I IntegrationHelper: --------------- Chartboost --------------
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: >>>> Chartboost - NOT VERIFIED
> 08-19 11:03:50.653 19490 19490 I IntegrationHelper: --------------- HyprMX --------------
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: >>>> HyprMX - NOT VERIFIED
> 08-19 11:03:50.653 19490 19490 I IntegrationHelper: --------------- UnityAds --------------
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.653 19490 19490 E IntegrationHelper: >>>> UnityAds - NOT VERIFIED
> 08-19 11:03:50.653 19490 19490 I IntegrationHelper: --------------- Vungle --------------
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: >>>> Vungle - NOT VERIFIED
> 08-19 11:03:50.654 19490 19490 I IntegrationHelper: --------------- InMobi --------------
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: >>>> InMobi - NOT VERIFIED
> 08-19 11:03:50.654 19490 19490 I IntegrationHelper: --------------- Facebook --------------
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: >>>> Facebook - NOT VERIFIED
> 08-19 11:03:50.654 19490 19490 I IntegrationHelper: --------------- Fyber --------------
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.654 19490 19490 E IntegrationHelper: >>>> Fyber - NOT VERIFIED
> 08-19 11:03:50.654 19490 19490 I IntegrationHelper: --------------- MediaBrix --------------
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: >>>> MediaBrix - NOT VERIFIED
> 08-19 11:03:50.655 19490 19490 I IntegrationHelper: --------------- Tapjoy --------------
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: >>>> Tapjoy - NOT VERIFIED
> 08-19 11:03:50.655 19490 19490 I IntegrationHelper: --------------- AdMob --------------
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: >>>> AdMob - NOT VERIFIED
> 08-19 11:03:50.655 19490 19490 I IntegrationHelper: --------------- MoPub --------------
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: >>>> MoPub - NOT VERIFIED
> 08-19 11:03:50.655 19490 19490 I IntegrationHelper: --------------- Maio --------------
> 08-19 11:03:50.655  1871  1998 I AppManager: dependence has been existed:19490 -> 12124
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: Adapter - MISSING
> 08-19 11:03:50.655 19490 19490 E IntegrationHelper: >>>> Maio - NOT VERIFIED
> 08-19 11:03:50.656  1871  1998 I AppManager: dependence has been existed:19490 -> 12124
> 08-19 11:03:50.658 19490 19702 W IntegrationHelper: --------------- Google Play Services --------------
> 08-19 11:03:50.658 19490 19702 I IntegrationHelper: Google Play Services - VERIFIED
> 08-19 11:03:50.659 19490 19490 D com.distriqt.IronSource: IronSourceController::setConsent( true )
> 08-19 11:03:50.659 19490 19490 I API     : setConsent : true
>

**Comment by ventr1x** [comment]
I guess it doesn't work as the mediators also need to be recompiled. Packing with Air32 works, AIR33 doesn't.

**Comment by marchbold** [comment]
Are you attempting to package a 64bit build? The mediation ANEs will need to be updated to include a 64bit version, otherwise there won't be a version for the packager to use and IronSrc will not find the mediators when running.
